### PR TITLE
Add bootsnap

### PR DESCRIPTION
**Pull request by ginty**
Adds the bootsnap gem to Origen to speed up application boot times - https://github.com/Shopify/bootsnap

This is on by default, but can be disabled at site/app/user level via a new site config parameter - `use_bootsnap`.
It is not enabled on Windows due to the bootsnap gem not supporting it.

From experiments in #288, this is expected to speed up Origen application boot times by several seconds and should be a noticeable speed improvement to the user.

Note that it is slower the first time it is run while the cache is created in `tmp/cache`.

### CODE REVIEW

**Comment by info-rchitect** [comment]
@ginty seems too simple for what is gained but just shows there are clever folks in the open space universe.  approved

**Comment by pderouen** [comment]
@ginty I just ran from a Windows 7 install with bootsnap enabled. "origen test" passed.

**Comment by pderouen** [comment]
Here's the times I measured executing "origen -v" inside an app (using powershell measure-command)

Without bootsnap
TotalSeconds      : 12.7561151

With bootsnap
TotalSeconds      : 6.1414542

Back to without bootsnap
TotalSeconds      : 12.6434103

**Comment by ginty** [comment]
@pderouen, I guess bootsnap helps a bit, that's pretty bad numbers though :-(

**Comment by pderouen** [comment]
It was actually a little slower with bootsnap enabled.  But, it loaded and ran just fine and I could see the cache it created. Should we enable it on Windows?  It wouldn't actually be used unless site config or the app enables it, right?  We'd need to update the windows install to include the bootsnap gem install.

**Comment by ginty** [comment]
@info-rchitect, does Pry work OK with this update? I saw some comments in the bootsnap issues which suggest that it may not.

**Comment by info-rchitect** [comment]
@ginty I added bootsnap to my app and have been able to use pry (step, next, etc.) alright.

**Comment by ginty** [comment]
OK, thanks @info-rchitect 

Anyone object to going ahead and releasing this?

**Comment by chrisnappi** [comment]
No, go for it.

**Comment by pderouen** [comment]
I have no issue with it. Do any of the docs need to be updated?

**Comment by ginty** [comment]
> Do any of the docs need to be updated?

Don't think so, this _should_ be a low level implementation detail that users never need to worry about.

If we find that this is not the case and there are some users who need to turn it off, we can reconsider the default setting and how we want to document it.

**Pull request merged**
