### PR TITLE
reverted automatically setting pin type

### PR DESCRIPTION
**Pull request by info-rchitect**
Related to issue #415 

@ginty If you point me in the right direction i can try to add a spec test for the current behavior that got broken.

### CODE REVIEW

**Comment by ginty** [comment]
Thanks a lot for the quick patch!

I think the test just needs to be `pin(:blah).type.should == nil` whenever no type is specified.

As long as that passes, you can keep around your additional types if you want?

**Comment by info-rchitect** [comment]
> Thanks a lot for the quick patch!
> 
> I think the test just needs to be `pin(:blah).type.should == nil` whenever no type is specified.
> 
> As long as that passes, you can keep around your additional types if you want?

OK will keep the additional types, one sec.

**Comment by priyavadan** [comment]
@info-rchitect looks good to me, thanks for the quick fix!

**Comment by info-rchitect** [comment]
Good to merge?  If so I will make a patch release.

**Comment by priyavadan** [comment]
ok from my end. 

@Jiangliu23 can you confirm if this branch fixes your use case/issue ?

**Comment by jiangliu23** [comment]
> ok from my end.
> 
> @jiangliu23 can you confirm if this branch fixes your use case/issue ?

thanks for the fix, i just confirmed in my environment, this branch no longer shows the issue. cheers.

**Review by priyavadan — APPROVED** [review]
good to go!

**Pull request merged**
