### PR TITLE
Added in 'has_key?' and 'rm_session_file' methods to the session store

### PR DESCRIPTION
**Pull request by info-rchitect**
convenient way to check if a key already exists.

### CODE REVIEW

**Comment by ginty** [comment]
Looks fine, need to fix the build error though (most likely a lint error) before we can merge

**Comment by info-rchitect** [comment]
is there something I need to fix?

**Comment by ginty** [comment]
Looks like it, the build is still failing, you should be able to click on that and click through to a log to find out what the problem is

**Comment by info-rchitect** [comment]
OK  I cannot see anything wrong with that file.  it shows I have added some methods and that is it.  origen specs passes with flying colors.  wtf?

**Pull request closed without merging**
