### PR TITLE
Feature/reserved keyword display

### PR DESCRIPTION
**Pull request by priyavadan**

### CODE REVIEW

**Comment by priyavadan** [comment]
Can i get an approval please?

@ginty @chrisnappi @coreyeng @redxeth

**Comment by ginty** [comment]
Can we downgrade the log ouput?
Success should be reserved for when Origen successfully produces something, probably `Origen.log.debug` is better suited here

**Review by ginty — APPROVED** [review]
LGTM

**Comment by priyavadan** [comment]
Thanks, will wait for builds to finish and then merge!

**Pull request merged**
