### PR TITLE
Cleaned up Origen::Clocks::Clock and added in feature to disable crea…

### PR DESCRIPTION
**Pull request by info-rchitect**
…ting sub_blocks for clock users.

### CODE REVIEW

**Comment by info-rchitect** [comment]
Hello everyone.  @Ginty is out on training, can some of you please check this and review it today?  I have some more PRs and would like to close this before adding to it.

**Comment by pderouen** [comment]
@info-rchitect I don't have any experience with this feature. So, I don't have much of an opinion on the matter. I guess the only concern I would bring up is backwards compatibility. Seems like these changes are not designed to support backwards compatibility. Was that the agreed upon intention?

**Comment by info-rchitect** [comment]
thx @pderouen yes this is a breaking change but I believe I am the only one using it now.  The attributes being changed were based on internal feedback designed to improve clarity.  Going forward to v1.0 the goal is to be backwards compatible.

**Comment by pderouen** [comment]
OK, I see that you added this module in October.  I agree there's likely nobody else using it yet.

**Comment by pderouen** [comment]
...sorry, clicked the wrong button just now.

**Comment by info-rchitect** [comment]
@welguisz are you using this module?

**Comment by info-rchitect** [comment]
thx @pderouen

**Comment by priyavadan** [comment]
lgtm!

**Comment by info-rchitect** [comment]
thanks everyone.  merging...

**Pull request merged**
