### PR TITLE
Sync to RGen v2.6.6

### PR DESCRIPTION
**Pull request by priyavadan**
Attempt 1 at the Sync. Too many changes, will need to review carefully to see if something was missed.

Thanks,
Priyavadan

### CODE REVIEW

**Comment by priyavadan** [comment]
@ginty can we get this merged soon? Thx

**Comment by welguisz** [comment]
@ginty ... When you get this merge, I will move my app from using RGen v2.6.6 to using Origen.

**Comment by ginty** [comment]
@welguisz, does it look ok to you?

**Comment by welguisz** [comment]
I went through the changes made for my app and they are there.  So I am great with the release.

**Pull request merged**
