### PR TITLE
Additional session store methods and basic spec tests

### PR DESCRIPTION
**Pull request by info-rchitect**

### CODE REVIEW

**Comment by info-rchitect** [comment]
I don't see how the coverage could go down so much, i didn't touch any of the files coveralls is complaining about.  I added a new spec file database_spec.rb so the coverage should go up.

**Comment by ginty** [comment]
Do we need to have the keys and user_keys methods?

Should we just have the keys method which does what the user_keys method does?

**Comment by info-rchitect** [comment]
well the users_keys gets rid of the keys that the user did not make, in essence the overhead keys.  we could make it an option for the keys method:

~~~ruby
def keys(options = {})
  options = {
    user_created_only: false
  }.update(options)
  if options[:user_created_only]
    store.keys.reject { |k| k.to_s.match(/refresh_interval_in_minutes/) }
  else
    store.keys
  end
end
~~~

Thoughts?

**Comment by ginty** [comment]
Understood, the question is really why would a user ever want to know about the internal use/overhead keys?

**Comment by info-rchitect** [comment]
I don't think they would, they just want their keys.  So you mean you want this:

~~~ruby
def keys
    store.keys.reject { |k| k.to_s.match(/refresh_interval_in_minutes/) }
end
~~~

**Comment by ginty** [comment]
Yep, though something like this should be easier to extend in future if we need to screen more keys:

~~~ruby
def keys
  store.keys - [:refresh_interval_in_minutes]
end
~~~

**Comment by ginty** [comment]
Is this comment about not being able to delete items from the session no longer valid?

https://github.com/Origen-SDK/origen/blob/master/templates/web/guides/misc/session.md.erb#L54

If so, could you update it accordingly?
Thanks!

**Comment by info-rchitect** [comment]
The CI build failure was only on one version of Ruby and it has nothing to do with the PR.  Can we approve this?

image

**Comment by info-rchitect** [comment]
thanks very much!

**Comment by ginty** [comment]
Included in 0.20.3

**Pull request merged**
