### PR TITLE
Added new class to specs portion of origen

### PR DESCRIPTION
**Pull request by welguisz**
Added a Features module to the Specs seciton of Origen.

This allows for a one page document to be created that lists the features and sub features for a piece of Silicon.  Allows granularity based off of the feature and the list of products within that device.

### CODE REVIEW

**Comment by priyavadan** [comment]
@welguisz looks like the CI check has failed, could you please look?

**Comment by welguisz** [comment]
I see the failure and will be making the change ... going to run origen specs before committing again

**Comment by welguisz** [comment]
This should be ready to go.  Let me know if there are any other issues with it.

**Comment by welguisz** [comment]
@priyavadan Travis CI is passing but coveralls is failing.  It says that my coverage dropped by 0.1%.  Cool to merge and do a release?

**Comment by ginty** [comment]
Hi @welguisz, 
Yep we can go ahead and merge, but note that the drop in coverage is indicating that new code/features have been added here without any test coverage of them.
As we are still getting used to this process we can turn a blind eye for now, but note that in future we will start knocking back feature additions that don't come with test coverage.
Thanks,
Stephen

**Comment by welguisz** [comment]
When say "test coverage", are you suggesting that it has spec tests written for them?

**Comment by ginty** [comment]
Yes

**Comment by welguisz** [comment]
Will do that today so that this is in alignment with the ongoing push to have "Every new feature come with test coverage."

**Comment by ginty** [comment]
Cool thanks, btw if you run "origen specs -c" you will get a coverage report generated that you can view in your browser to see what bits of your code are not hit.

The updates in this PR are now released as Origen 0.6.0.

**Pull request merged**
