### PR TITLE
Added in support for evaluating spec formulas that reference a power …

### PR DESCRIPTION
**Pull request by info-rchitect**
…domain.  only took 4 years to get this working!

~~~ruby
  it 'can evaluate references to power domains' do
    @dut.power_domains(:vmemio).nominal_voltage.should == 1.35
    @dut.specs(:memio_voh).max.exp.should == ":vmemio * 0.8"
    @dut.specs(:memio_voh).max.value.should == 1.08
    @dut.specs(:direct_ref_spec).max.exp.should == :vmemio
    @dut.specs(:direct_ref_spec).max.value.should == 1.35
  end

  it 'can evaluate references to clocks' do
    @dut.clocks(:core_clk).freq_target.should == 1.2.Ghz
    @dut.specs(:fmin).min.exp.should == ":core_clk * 0.9"
    @dut.specs(:fmin).min.value.should == 1.08.Ghz
  end
~~~ #

### CODE REVIEW

**Comment by info-rchitect** [comment]
@welguisz should the console print method display the spec formula and the value or one or the other?

**Comment by info-rchitect** [comment]
OK I slightly changed my mind and would like to close this PR so I can start a new one to handle single quotes within a spec expression/formula.  Please reply urgently if that is not OK.

**Comment by ginty** [comment]
You don't really need to close this, just keep pushing the updates to your fork and they will appear here, and you can edit the summary above as required

**Comment by info-rchitect** [comment]
Added in commit to handle [this issue](https://github.com/Origen-SDK/origen/issues/146)

**Pull request merged**
