### PR TITLE
Changed nokogiri from locking to 1.7.2 to require 1.7.2 or greater.

### PR DESCRIPTION
**Pull request by welguisz**
Here is the note that I put to all NXP users, which can be used for other companies that use Origen:

To all Origen users: In a future release, we will be changing the way that Origen references nokogiri. Currently, origen sets nokogiri to version 1.7.2. In this upcoming release, we will expand the versions of Nokogiri to be 1.7.2 or greater. If you are having issues after this release, here are two ways to fix the issue:

In your gemspec file:
```ruby
spec.add_runtime_dependency "nokogiri", "1.7.2"
```

OR

In your Gemfile,
```ruby
gem "nokogiri", "1.7.2"
```
When we do release this change, we will update this note.

### CODE REVIEW

**Comment by ginty** [comment]
@chrisnappi, @coreyeng, @pderouen, what's your thoughts here.

Is the advice @welguisz gave on Yammer good enough, or do we need more?

**Comment by pderouen** [comment]
Seems fine to me.

**Comment by info-rchitect** [comment]
@ginty can we merge this?

**Comment by ginty** [comment]
I guess, @chrisnappi  and @coreyeng are effectively blessing it by not replying.

I would change it though, the change should be to take nokogiri out of the dependencies list altogether, Origen doesn't need it.

**Comment by info-rchitect** [comment]
@welguisz Can you comment on @ginty suggestion and fix the conflicts here?  We would really like to get this change merged so we don't have to do it on our side.

**Comment by welguisz** [comment]
@info-rchitect ... sorry for the delay.  I have been on a critical project and just finished it yesterday.  I just took the dependency out to nokogiri.  When I ran 'bundle update', the Gemfile.lock did remove the nokogiri gem.  Running specs and lint right now before commiting and pushing.

**Comment by info-rchitect** [comment]
@welguisz no problem, thx for closing this today.

**Comment by ginty** [comment]
Sorry, didn't realize it was used in some specs.

You could add it to the Gemfile and revert the specs if you prefer.

**Comment by welguisz** [comment]
@info-rchitect   When I run with this fix, I am getting the following failure:

```
    1) Origen Specs Module can evaluate references to power domains
     Failure/Error: @dut.specs(:direct_ref_spec).max.value.should == 1.35
     
       expected: 1.35
            got: "vmemio" (using ==)
     # ./spec/specs_spec.rb:494:in `block (2 levels) in <top (required)>'
     # ./config/commands.rb:19:in `<top (required)>'
     # ./lib/origen/commands.rb:183:in `require'
     # ./lib/origen/commands.rb:183:in `<top (required)>'
```

Can you help me debug this so we can merge this...

**Comment by info-rchitect** [comment]
@welguisz there are no issues with more recent PRs regarding the specs rspec tests.  I expect your PR must not have all of the latest files.?  Is that even possible?

**Comment by info-rchitect** [comment]
@welguisz there are no issues with more recent PRs regarding the specs rspec tests.  I expect your PR must not have all of the latest files.?  Is that even possible?

**Comment by welguisz** [comment]
@info-rchitect ... I was looking at the failing test and have no idea what is happening.  Going forward, it would be better for all of us to make our tests better.  For example, the failing section is:

```ruby
  it 'can evaluate references to power domains'  do
    pending('Direct Reference Specification is not working as expected for')
    @dut.power_domains(:vmemio).nominal_voltage.should == 1.35
    @dut.specs(:memio_voh).max.exp.should == ":vmemio * 0.8"
    @dut.specs(:memio_voh).max.value.should == 1.08
    @dut.specs(:direct_ref_spec).max.exp.should == :vmemio
    @dut.specs(:direct_ref_spec).max.value.should == 1.35
    @dut.power_domains(:voffset).nominal_voltage.should == 0.25
    @dut.specs(:memio_voh_offset).max.exp.should == ":vmemio * 0.8 - :voffset"
    @dut.specs(:memio_voh_offset).max.value.should == 0.83
  end
```
I added the line \#pending so the tests will run, fail, but will be ignored for PASS/FAIL status.  A better format would be:

```ruby
  describe 'can evaluate references to power domains' do
    it 'Checks that power domains can return nominal voltage' do
       @dut.power_domains(:vmemio).nominal_voltage.should == 1.35
    end
    it 'Checks that expression for specs returns string and equation' do
    end
  end
```

This way, I can just skip one test instead of 8 tests.

**Comment by info-rchitect** [comment]
not sure when I can get to this, currently making a Perforce wrapper for revision control that will gate us moving forward.

**Comment by info-rchitect** [comment]
@welguisz @ginty so this is ready to go?

**Pull request merged**
