### PR TITLE
Updating rubocop ver to 0.54 and updating config files accordingly

### PR DESCRIPTION
**Pull request by vbb9857**

### CODE REVIEW

**Comment by priyavadan** [comment]
@vbb9857 First PR! :) Good work!

**Comment by info-rchitect** [comment]
Nice work! :grin:

**Comment by ginty** [comment]
Thanks a lot for doing this.

Could you take a look at the build fails below, click on details then from there the Ruby version to see the log of why it failed.
It looks like the `origen lint` command crashed.

Does it work locally for you?

**Comment by priyavadan** [comment]
> Thanks a lot for doing this.
> 
> Could you take a look at the build fails below, click on details then from there the Ruby version to see the log of why it failed.
> It looks like the `origen lint` command crashed.
> 
> Does it work locally for you?

@ginty  seems like locally, no issues running "origen lint" , suggestions?

image

**Comment by info-rchitect** [comment]
@vbb9857 Is there a reason you chose 0.54.0 vs the latest 0.77.0?

**Comment by vbb9857** [comment]
> @vbb9857 Is there a reason you chose 0.54.0 vs the latest 0.77.0?

Hi @info-rchitect, no apparent reason for choosing that ver. Is there any recommendation of what I should be using?

**Comment by info-rchitect** [comment]
> @vbb9857 Is there a reason you chose 0.54.0 vs the latest 0.77.0?
> 
> Hi @info-rchitect, no apparent reason for choosing that ver. Is there any recommendation of what I should be using?

I think people usually use the latest unless there is Ruby version conflict or a gem dependency conflict.

**Comment by info-rchitect** [comment]
Does anyone object to moving to the latest version of rubocop?

**Comment by priyavadan** [comment]
Going to decline this PR , if work on it has stalled...

@vbb9857 @info-rchitect

**Comment by info-rchitect** [comment]
Fine with me, though we should migrate to the latest rubocop at some time

**Pull request closed without merging**
